#################################
# Server 설정
#################################
server:
  port: ${cnf.port}
#################################
# Spring 설정
#################################
spring :
  application :
    name : data_loader
  port: ${cnf.port}
  datasource:
    # FMS
#    url: jdbc:mysql://uconnect.conv.site:33062/ufmsnew?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    # DX
#    url: jdbc:mysql://dbms.conv.site:33060/IIOT_SF?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
#    username: IIOTADM
#    password: "IIOTADM1234!"
    url: jdbc:mysql://localhost.querypie.com:40081/IIOT_SF?rewriteBatchedStatements=true&useServerPrepStmts=false
    username: querypie
    password: "6514087de86f2360"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        order_inserts: true
        jdbc.batch_size: 100
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace

db-table:
  batch-size: 100
  startIdx: 40000